package com.increditek.lgapi.service;

import com.increditek.lgapi.domain.JournalEntry;
import com.increditek.lgapi.exception.ItemNotFoundException;
import com.increditek.lgapi.repository.JournalEntryRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import java.time.LocalDate;

@Service
public class JournalEntryService {
    private final JournalEntryRepository journalEntryRepository;

    public JournalEntryService(JournalEntryRepository journalEntryRepository) {
        this.journalEntryRepository = journalEntryRepository;
    }

    public JournalEntry findById(Long id) {
        return journalEntryRepository.findById(id).orElseThrow(() -> new ItemNotFoundException("Count not find Journal Entry with id: " + id));
    }

    public Page<JournalEntry> findByDateRange(int page, int pageSize, Boolean includeAutoGenerated, LocalDate startDate, LocalDate endDate) {
        return journalEntryRepository.findAllByAutoGeneratedAndDateBetween(PageRequest.of(page, pageSize), includeAutoGenerated, startDate, endDate);
    }
    public JournalEntry findByJournalEntryId(Long id) {
        return journalEntryRepository.findById(id).orElseThrow(() -> new ItemNotFoundException("Count not find Journal Entry with id: " + id));
    }
}
