package com.increditek.lgapi.repository;

import com.increditek.lgapi.domain.JournalEntry;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;

import java.time.LocalDate;

public interface JournalEntryRepository  extends JpaRepository<JournalEntry, Long> {
    Page<JournalEntry> findAllByAutoGeneratedAndDateBetween(Pageable p, Boolean autogenerated, LocalDate startDate, LocalDate endDate);
}
