package com.increditek.lgapi.controller;

import com.increditek.lgapi.domain.JournalEntry;
import com.increditek.lgapi.domain.PageableResponse;
import com.increditek.lgapi.service.JournalEntryService;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.time.LocalDate;

@RestController
@RequestMapping("/journal-entries")
public class JournalEntryController {
    private final JournalEntryService journalEntryService;

    public JournalEntryController(JournalEntryService journalEntryService) {
        this.journalEntryService = journalEntryService;
    }

    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public PageableResponse getJournalEntries(HttpServletRequest request,
                                             @RequestParam(defaultValue = "0") int page,
                                             @RequestParam(defaultValue = "100") int pageSize,
                                             @RequestParam(value = "includeAutoGenerated", required = true, defaultValue = "false") Boolean includeAutoGenerated,
                                             @RequestParam("startDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
                                             @RequestParam("endDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate) {
        return new PageableResponse("lgapi/journal-entries", journalEntryService.findByDateRange(page, pageSize, includeAutoGenerated, startDate, endDate), request.getRequestURL().toString());
    }

    @GetMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public JournalEntry getById(@PathVariable Long id) {
        return journalEntryService.findById(id);
    }
}
